#ifndef _GAME_STATES_H_
#define _GAME_STATES_H_

enum E_GAME_STATE
{
	E_GAME_STATE_MAIN_MENU,
	E_GAME_STATE_HIGH_SCORES,
	E_GAME_STATE_SELECT_DIFFICULTY,
	E_GAME_STATE_IN_GAME,
	E_GAME_STATE_LOSE_GAME,
	E_GAME_STATE_WIN_GAME
};

#endif
