#include "EnemyShip.h"
#include "Core/Renderer/ConsoleColours.h"

const int ENEMY_SPRITE_WIDTH = 18;
const int ENEMY_SPRITE_HEIGHT = 13;

CHAR_INFO EnemySprite0[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},			{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},			{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK}
	},
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},			{0, BACKGROUND_BLACK},		{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_DARK_GREY},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK}
	},

};

CHAR_INFO EnemySprite1[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK}
	},
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK}
	},

};

CHAR_INFO EnemySprite2[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_BLUE},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK}
	},
	{
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_BRIGHT_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK}
	},

};


EnemyShip::EnemyShip()
	:m_bInitialised(false)
	, m_AnimationTimer(0.0f)
	, m_Active(false)
	, m_FireRate(0)

{
}

EnemyShip::~EnemyShip()
{
}

void EnemyShip::Initialise(Vector2& position, int fireRate, int sprite, int speed, float initialTime)
{
	m_FireRate = fireRate;

	m_AnimationTimer = initialTime;
	
	m_EnemyType = sprite;

	m_Speed = speed;

	if (sprite == 1)
		AnimatedSprite::Initialise(&EnemySprite1[0][0], Vector3(ENEMY_SPRITE_WIDTH, ENEMY_SPRITE_HEIGHT, ENEMY_SPRITE_ANIMATION_FRAMES));
	else if (sprite == 2)
		AnimatedSprite::Initialise(&EnemySprite2[0][0], Vector3(ENEMY_SPRITE_WIDTH, ENEMY_SPRITE_HEIGHT, ENEMY_SPRITE_ANIMATION_FRAMES));
	else
		AnimatedSprite::Initialise(&EnemySprite0[0][0], Vector3(ENEMY_SPRITE_WIDTH, ENEMY_SPRITE_HEIGHT, ENEMY_SPRITE_ANIMATION_FRAMES));

	Vector2 startPosition(position.x, position.y / 2);
	SetPosition(startPosition);

	m_bInitialised = true;
}

bool EnemyShip::Update(float deltaTime)
{
	if (!m_bInitialised || !m_Active)
		return false;
		
	SetPosition(GetPosition().x - m_Speed, GetPosition().y);

	m_AnimationTimer += deltaTime;
	if (m_AnimationTimer >= 1.0f)
	{
		if (GetAnimationFrame() == 2)
		{
			m_AnimationTimer -= 0.15f;
			SetAnimationFrame(3);
		}
		else if (GetAnimationFrame() == 3)
		{
			m_Active = false;
		}
		else
		{
			m_AnimationTimer -= 1.0f;
			SetAnimationFrame(GetAnimationFrame() == 0 ? 1 : 0);
		}

	}
	
	return FireWeapon();
}

bool EnemyShip::FireWeapon()
{
	bool shouldFire = false;
	int chance = rand() % 1000;

	if (m_FireRate > chance) //if fire rate is greater than random number, enemy should fire.
	{
		shouldFire = true;
	}

	return shouldFire;
}

void EnemyShip::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised || !m_Active)
		return;

	AnimatedSprite::Render(pRenderer);
}

void EnemyShip::Explode()
{
	if (GetAnimationFrame() < 2)
	{
		m_AnimationTimer = 0.85f;
		SetAnimationFrame(2);
	}

	m_Active = false;
}

int EnemyShip::GetEnemyType()
{
	return m_EnemyType;
}