#include "Player.h"
#include "Core/Renderer/ConsoleColours.h"

const int SCORE_SPRITE_SIZE = 11;

int Player::MOVEMENT_SPEED = 5;

CHAR_INFO ShipSprite[] =
{
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_GREY},	{0, BACKGROUND_GREY},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW}, {0, BACKGROUND_TURQOISE},	{0, BACKGROUND_TURQOISE},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},	{0, BACKGROUND_YELLOW},
	{0, BACKGROUND_GREY},	{0, BACKGROUND_GREY},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},		{0, BACKGROUND_RED},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_RED},	{0, BACKGROUND_RED},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},		{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_WHITE},	{0, BACKGROUND_YELLOW}, {0, BACKGROUND_YELLOW},		{0, BACKGROUND_WHITE},		{0, BACKGROUND_WHITE},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK},	{0, BACKGROUND_BLACK}
};


Vector2 shipSize(13, 9);

Player::Player()
:m_bInitialised(false)
{
}

Player::~Player()
{
}

void Player::Initialise(Vector2& position)
{

	Sprite::Initialise(ShipSprite, shipSize);

	Vector2 startPosition(0, position.y / 2 - (Sprite::GetSize().y / 2));
	SetPosition(startPosition);

	m_bInitialised = true;
}

void Player::Update()
{
	if (!m_bInitialised)
		return;

	if (UpKeyPressed())
		MoveUp();

	if (DownKeyPressed())
		MoveDown();
}

void Player::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;

	Sprite::Render(pRenderer);
}

void Player::MoveUp()
{
	SetPosition(Vector2(GetPosition().x, GetPosition().y - MOVEMENT_SPEED));

	if (GetPosition().y < SCORE_SPRITE_SIZE) //Stops player from going above the screen.
	{
		MoveDown();
	}
}

void Player::MoveDown()
{
	SetPosition(Vector2(GetPosition().x, GetPosition().y + MOVEMENT_SPEED));

	if (GetPosition().y + GetSize().y > SCREEN_HEIGHT) //Stops player from going below the screen.
	{
		MoveUp();
	}
}

bool Player::UpKeyPressed()
{
	return (GetKeyState(VK_UP) < 0);
}

bool Player::DownKeyPressed()
{
	return (GetKeyState(VK_DOWN) < 0);
}
